import type { Metadata } from "next";
import { VideoProvider } from "../provider/videoProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <VideoProvider>{children}</VideoProvider>
      </body>
    </html>
  );
}
